# Whether to connect to the SQL server. Enable this if you want the bot to
# be able to store whitelisted users.
enableSql: false

# MySQL Database Details
# The bot requires SELECT, INSERT, CREATE and DELETE privileges.
mysql:
  host: "127.0.0.1"
  database: "database"
  port: "3306"
  username: "root"
  password: "password"

# Add player overrides
overrides:
  - skyefoxie

discord:
  # Bot token the plugin should use.
  token: 'discord token here'

  # The ID of the guild you want the bot to listen in.
  guildId: 'guild id here'

  # The prefix the bot should use.
  prefix: '-'

  # Whether users are able to run the `-minecraft <username>` command
  # and verify themselves.
  enableSelfWhitelisting: true

  # Enable ban syncing. Users will be banned on both Discord and Minecraft.
  # Bot will require permissions to ban users on Discord!!
  enableBanSync: true

  # Restrict Discord users to one Minecraft account. If set to false, users can connect
  # as many Minecraft accounts to their Discord account as they want.
  oneAccountPerUser: true

  roles:
    # The role users are required to have to be able to be whitelisted.
    requiredRole:
      enabled: false
      roleId: 'required role id here'

    # The role users are granted once whitelisted.
    grantedRole:
      enabled: false
      silent: false
      roleId: ''

